baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'
enableRobotsTXT = true
paginate = 10
paginatePath = "page"

[minify]
  disableXML = true
  [minify.tdewolff.html]
    keepWhitespace = false

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    min = "0.148.2"
    extended = false
